### ISSUE TITLE
TypeError: RCore_gdiff expected 2 arguments, got 3

### ISSUE THREAD

**Issue by dhxkgozj** [radare/radare2-bindings#110]
root@ubuntu:~/radare2/radare2-bindings/python# python test-ragdiff2.py /bin/sh /bin/sh
Traceback (most recent call last):
  File "test-ragdiff2.py", line 241, in <module>
    main()
  File "test-ragdiff2.py", line 236, in main
    rd.diff()
  File "test-ragdiff2.py", line 208, in diff
    self.c.gdiff(self.c2, True)
TypeError: RCore_gdiff expected 2 arguments, got 3

**Comment by radare** [comment]
just remove the last parameter. its fixed in master now
