### ISSUE TITLE
Cannot create r2pipe object without filename

### ISSUE THREAD

**Issue by Manouchehri** [radare/radare2-bindings#127]
```python

C:\IntelPython27\python.exe C:\Users\David\.IntelliJIdea2016.2\config\plugins\python\helpers\pydev\pydevconsole.py 5741 5742
Python 2.7.11 (default, Jun  2 2016, 13:36:37) [ICC v.1600 64 bit (amd64) with MSC v.1500 CRT]
Type "copyright", "credits" or "license" for more information.

IPython 4.1.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
PyDev console: using IPython 4.1.1

import sys; print('Python %s on %s' % (sys.version, sys.platform))
sys.path.extend(['C:\\Users\\Dave\\IdeaProjects\\radare2-binexport2'])

Python 2.7.11 (default, Jun  2 2016, 13:36:37) [ICC v.1600 64 bit (amd64) with MSC v.1500 CRT] on win32
In[2]: import r2pipe
In[3]: r2p = r2pipe.open()
Traceback (most recent call last):
  File "C:\IntelPython27\lib\site-packages\IPython\core\interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-7328f2caab95>", line 1, in <module>
    r2p = r2pipe.open()
  File "C:\IntelPython27\lib\site-packages\r2pipe\__init__.py", line 148, in __init__
    self.process = Popen(cmd, shell=False, stdin=PIPE, stdout=PIPE)
  File "C:\IntelPython27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\IntelPython27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
In[4]: r2p
Traceback (most recent call last):
  File "C:\IntelPython27\lib\site-packages\IPython\core\interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-e6021daf2b78>", line 1, in <module>
    r2p
NameError: name 'r2p' is not defined
```

**Comment by Manouchehri** [comment]
Doing it in a normal Python console session seems to work.

```python
Python 2.7.11 (default, Jun  2 2016, 13:36:37) [ICC v.1600 64 bit (amd64) with MSC v.1500 CRT] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import r2pipe
>>> r2p = r2pipe.open()
Missing file to open
>>> r2p
<r2pipe.open instance at 0x000000000350BC88>
```

**Comment by Manouchehri** [comment]
Personal system issues, not r2pipe's fault. Fixed it.

**Comment by radare** [comment]
Tahts expected unless u run this from jnside r2
