### ISSUE TITLE
ImportError: No module named _r_core

### ISSUE THREAD

**Issue by blshkv** [radare/radare2-bindings#146]
Hi I can't figure out that is the issue and need your help.
Here is the output:
```
bash$ python
Python 2.7.12 (default, Jan  3 2017, 08:23:47) 
[GCC 5.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import rc.r_core
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named rc.r_core
>>> import r2.r_core
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/r2/r_core.py", line 32, in <module>
    _r_core = swig_import_helper()
  File "/usr/lib64/python2.7/site-packages/r2/r_core.py", line 24, in swig_import_helper
    import _r_core
ImportError: No module named _r_core
```

Here is the list of files which I got after installation:
```
/usr
/usr/lib64
/usr/lib64/python2.7
/usr/lib64/python2.7/site-packages
/usr/lib64/python2.7/site-packages/r2
/usr/lib64/python2.7/site-packages/r2/__init__.py
/usr/lib64/python2.7/site-packages/r2/__init__.pyc
/usr/lib64/python2.7/site-packages/r2/__init__.pyo
/usr/lib64/python2.7/site-packages/r2/_r_asm.so
/usr/lib64/python2.7/site-packages/r2/_r_bin.so
/usr/lib64/python2.7/site-packages/r2/r_asm.py
/usr/lib64/python2.7/site-packages/r2/r_asm.pyc
/usr/lib64/python2.7/site-packages/r2/r_asm.pyo
/usr/lib64/python2.7/site-packages/r2/r_bin.py
/usr/lib64/python2.7/site-packages/r2/r_bin.pyc
/usr/lib64/python2.7/site-packages/r2/r_bin.pyo
/usr/lib64/python2.7/site-packages/r2/r_core.py
/usr/lib64/python2.7/site-packages/r2/r_core.pyc
/usr/lib64/python2.7/site-packages/r2/r_core.pyo
/usr/lib64/radare2
/usr/lib64/radare2/1.2.1
/usr/lib64/radare2/1.2.1/lang_csharp.so
/usr/lib64/radare2/1.2.1/lang_duktape.so
/usr/lib64/radare2/1.2.1/lang_python.so
/usr/lib64/radare2/1.2.1/radare.lua
/usr/share
/usr/share/doc
/usr/share/doc/radare2-bindings-1.2.1
/usr/share/doc/radare2-bindings-1.2.1/README.md.bz2
/usr/share/doc/radare2-bindings-1.2.1/TODO.bz2
````

and relevant lib files of r2
```
/usr/lib64
/usr/lib64/libr2.so -> libr2.so.1.2.1
/usr/lib64/libr2.so.1.2.1
/usr/lib64/libr_anal.so -> libr_anal.so.1.2.1
/usr/lib64/libr_anal.so.1.2.1
/usr/lib64/libr_asm.so -> libr_asm.so.1.2.1
/usr/lib64/libr_asm.so.1.2.1
/usr/lib64/libr_bin.so -> libr_bin.so.1.2.1
/usr/lib64/libr_bin.so.1.2.1
/usr/lib64/libr_bp.so -> libr_bp.so.1.2.1
/usr/lib64/libr_bp.so.1.2.1
/usr/lib64/libr_config.so -> libr_config.so.1.2.1
/usr/lib64/libr_config.so.1.2.1
/usr/lib64/libr_cons.so -> libr_cons.so.1.2.1
/usr/lib64/libr_cons.so.1.2.1
/usr/lib64/libr_core.so -> libr_core.so.1.2.1
/usr/lib64/libr_core.so.1.2.1
/usr/lib64/libr_crypto.so -> libr_crypto.so.1.2.1
/usr/lib64/libr_crypto.so.1.2.1
/usr/lib64/libr_debug.so -> libr_debug.so.1.2.1
/usr/lib64/libr_debug.so.1.2.1
/usr/lib64/libr_egg.so -> libr_egg.so.1.2.1
/usr/lib64/libr_egg.so.1.2.1
/usr/lib64/libr_flag.so -> libr_flag.so.1.2.1
/usr/lib64/libr_flag.so.1.2.1
/usr/lib64/libr_fs.so -> libr_fs.so.1.2.1
/usr/lib64/libr_fs.so.1.2.1
/usr/lib64/libr_hash.so -> libr_hash.so.1.2.1
/usr/lib64/libr_hash.so.1.2.1
/usr/lib64/libr_io.so -> libr_io.so.1.2.1
/usr/lib64/libr_io.so.1.2.1
/usr/lib64/libr_lang.so -> libr_lang.so.1.2.1
/usr/lib64/libr_lang.so.1.2.1
/usr/lib64/libr_magic.so -> libr_magic.so.1.2.1
/usr/lib64/libr_magic.so.1.2.1
/usr/lib64/libr_parse.so -> libr_parse.so.1.2.1
/usr/lib64/libr_parse.so.1.2.1
/usr/lib64/libr_reg.so -> libr_reg.so.1.2.1
/usr/lib64/libr_reg.so.1.2.1
/usr/lib64/libr_search.so -> libr_search.so.1.2.1
/usr/lib64/libr_search.so.1.2.1
/usr/lib64/libr_socket.so -> libr_socket.so.1.2.1
/usr/lib64/libr_socket.so.1.2.1
/usr/lib64/libr_syscall.so -> libr_syscall.so.1.2.1
/usr/lib64/libr_syscall.so.1.2.1
/usr/lib64/libr_util.so -> libr_util.so.1.2.1
/usr/lib64/libr_util.so.1.2.1
/usr/lib64/pkgconfig
/usr/lib64/pkgconfig/r_anal.pc
/usr/lib64/pkgconfig/r_asm.pc
/usr/lib64/pkgconfig/r_bin.pc
/usr/lib64/pkgconfig/r_bp.pc
/usr/lib64/pkgconfig/r_config.pc
/usr/lib64/pkgconfig/r_cons.pc
/usr/lib64/pkgconfig/r_core.pc
/usr/lib64/pkgconfig/r_debug.pc
/usr/lib64/pkgconfig/r_flag.pc
/usr/lib64/pkgconfig/r_fs.pc
/usr/lib64/pkgconfig/r_hash.pc
/usr/lib64/pkgconfig/r_io.pc
/usr/lib64/pkgconfig/r_lang.pc
/usr/lib64/pkgconfig/r_magic.pc
/usr/lib64/pkgconfig/r_parse.pc
/usr/lib64/pkgconfig/r_reg.pc
/usr/lib64/pkgconfig/r_search.pc
/usr/lib64/pkgconfig/r_socket.pc
/usr/lib64/pkgconfig/r_syscall.pc
/usr/lib64/pkgconfig/r_util.pc
/usr/lib64/radare2
/usr/lib64/radare2/1.2.1
/usr/lib64/radare2/1.2.1/asm_LM32.so
/usr/lib64/radare2/1.2.1/asm_propeller.so
/usr/lib64/radare2/1.2.1/bin_xtr_dyldcache.so
/usr/lib64/radare2/1.2.1/parse_z80_pseudo.so
/usr/lib64/radare2/last -> 1.2.1
```

any ideas?

**Comment by blshkv** [comment]
This might be related to the issue #145 . There is seem an error during r_core compilation:
```
r_anal.vapi:9.3-9.7: warning: argument `lowercase_c_prefix' never used
r_db.vapi:5.3-5.7: warning: argument `name' never used
WARNING Method continue renamed to cont (don't ask where)
swig -small -O -o r_core_wrap.cxx -DG_BEGIN_DECLS -DG_END_DECLS -DG_GNUC_CONST -DSWIG_PYTHON_SILENT_MEMLEAK -I/usr/include/libr -c++ -c++ -python r_core.i
r_core.i:39: Warning 302: Identifier 'RCoreAsmHitVector' redefined (ignored) (Renamed from 'vector< RCoreAsmHit >'),
r_core.i:38: Warning 302: previous definition of 'RCoreAsmHitVector' (Renamed from 'vector< RCoreAsmHit >').
r_core.i:41: Warning 302: Identifier 'RAnalRefVector' redefined (ignored) (Renamed from 'vector< RAnalRef >'),
r_core.i:40: Warning 302: previous definition of 'RAnalRefVector' (Renamed from 'vector< RAnalRef >').
r_core.i:45: Warning 302: Identifier 'RAnalRefVector' redefined (ignored) (Renamed from 'vector< RAnalRef >'),
r_core.i:40: Warning 302: previous definition of 'RAnalRefVector' (Renamed from 'vector< RAnalRef >').
r_core.i:46: Warning 302: Identifier 'RAnalRefVector' redefined (ignored) (Renamed from 'vector< RAnalRef >'),
r_core.i:40: Warning 302: previous definition of 'RAnalRefVector' (Renamed from 'vector< RAnalRef >').
r_core.i:61: Warning 302: Identifier 'charVector' redefined (ignored) (Renamed from 'vector< char >'),
r_core.i:57: Warning 302: previous definition of 'charVector' (Renamed from 'vector< char >').
r_core.i:62: Warning 302: Identifier 'charVector' redefined (ignored) (Renamed from 'vector< char >'),
r_core.i:57: Warning 302: previous definition of 'charVector' (Renamed from 'vector< char >').
r_core.i:91: Warning 314: 'print' is a python keyword, renaming to '_print'
r_core.i:321: Warning 314: 'from' is a python keyword, renaming to '_from'
r_core.i:326: Warning 314: 'from' is a python keyword, renaming to '_from'
r_core.i:579: Warning 314: 'import' is a python keyword, renaming to '_import'
r_core.i:1938: Warning 314: 'del' is a python keyword, renaming to '_del'
r_core.i:1644: Warning 453: Can't apply (RAsmOp *OUTPUT). No typemaps are defined.
r_core.i:1649: Warning 453: Can't apply (RAsmOp *OUTPUT). No typemaps are defined.
g++ -fPIC -shared r_core_wrap.cxx -DG_BEGIN_DECLS -DG_END_DECLS -DG_GNUC_CONST -DSWIG_PYTHON_SILENT_MEMLEAK -I/usr/include/python2.7 -I/usr/include/python2.7 -march=native -O2 -pipe -DNDEBUG -I/usr/include/libr -o _r_core.so -lr_crypto -lr_magic -lr_fs -lr_socket -lr_syscall -lr_search -lr_reg -lr_egg -lr_bp -lr_parse -lr_anal -lr_io -lr_lang -lr_bin -lr_hash -lr_debug -lr_asm -lr_flag -lr_util -lr_io -lr_cons -lr_config -lr_core -L/usr/local/lib -L/usr/pkg/lib -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic
r_core_wrap.cxx: In function ‘int RCore_visual_cmd(RCore*, char*)’:
r_core_wrap.cxx:7380:37: error: invalid conversion from ‘char*’ to ‘int’ [-fpermissive]
   return r_core_visual_cmd(self, arg);
                                     ^
In file included from r_core_wrap.cxx:3311:0:
/usr/include/libr/r_core.h:240:11: note:   initializing argument 2 of ‘int r_core_visual_cmd(RCore*, int)’
 R_API int r_core_visual_cmd(RCore *core, int ch);
           ^
... r_core.so
... r_bin.so
... r_asm.so
make[1]: Leaving directory '/home/blshkv/radare2-bindings-1.2.1/python'
```

**Comment by radare** [comment]
Arr you using latest r2 and latest r2bindings from git?

**Comment by blshkv** [comment]
No, both are the latest release 1.2.1

**Comment by radare** [comment]
And do you have a previous installation in your system?

**Comment by blshkv** [comment]
no, I dont have it. Please see my patch above, there is really different type defined

**Comment by blshkv** [comment]
You can download 1.2.1 release and check yourself:
```
radare2-1.2.1/libr/include/r_core.h
R_API int r_core_visual_cmd(RCore *core, int ch);

radare2-bindings-1.2.1/vapi/r_core.vapi
        public int visual_cmd(string arg);
```

**Comment by radare** [comment]
wondering why it was building here… fixed in master, you just need to update the .vapi file, in fact this signature changed in master already

**Comment by blshkv** [comment]
You might want to release a new version sooner.  I'm closing this bug as the issue is fixed in git

**Comment by radare** [comment]
Theres a new release every 6 weeks. Can u wait for it? A minor release just for this can be done too.. but i would prefer to wait and distros can pick the patch if needed.

Next release will be March 13th

**Comment by blshkv** [comment]
The patch is simple but it's time consuming . Perhaps,  you could improve test cases so that it would  be possibile discover such errors in future.  There are way too many errors during compilation right now and it's tricky to understand which are relevant..

**Comment by radare** [comment]
no need to have test cases for that, r2b is already compiled in jenkins, but as long as im only checking travis lately i missed that. will put that into travis.

thx
