### ISSUE TITLE
Python r2pipe broken pipe error

### ISSUE THREAD

**Issue by SiD3W4y** [radare/radare2-bindings#175]
I am getting a broken pipe error in python while using r2pipe: 
`
Traceback (most recent call last):              
  File "example.py", line 4, in <module>        
    r2.cmd("aa")        
  File "/usr/lib/python3.6/site-packages/r2pipe/__init__.py", line 245, in cmd                  
    return self._cmd(cmd).strip()               
  File "/usr/lib/python3.6/site-packages/r2pipe/__init__.py", line 160, in _cmd_process         
    self.process.stdin.flush()                  
BrokenPipeError: [Errno 32] Broken pipe 
`
It is when using directly r2pipe like this
```python
import r2pipe

r2 = r2pipe.open("/bin/ls")
r2.cmd("aa") # Error here
```

However there isn't any problem when executing from inside r2 or when using the ccall:// uri.
For info I am using r2pipe for python v0.9.1 and r2 version 1.7.0-git 16296 @ linux-x86-64 git.1.6.0-1024-g41ce16b31.

**Comment by radare** [comment]
cant reproduce.

**Comment by radare** [comment]
r2pipe doesnt belongs to bindings
