### ISSUE TITLE
pip package bokken

### ISSUE THREAD

**Issue by crowell** [radare/radare2-bindings#64]
```
minishwoods tools/binaryninja-python ‹crowell_r2_integration› » pip install r2pipe
Downloading/unpacking r2pipe
  Downloading r2pipe-0.6.1.tar.gz
  Running setup.py (path:/tmp/pip-build-QGFUWR/r2pipe/setup.py) egg_info for package r2pipe
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-QGFUWR/r2pipe/setup.py", line 4, in <module>
        with open('README.rst') as readme_file:
    IOError: [Errno 2] No such file or directory: 'README.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-QGFUWR/r2pipe/setup.py", line 4, in <module>

    with open('README.rst') as readme_file:

IOError: [Errno 2] No such file or directory: 'README.rst'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-QGFUWR/r2pipe
Storing debug log for failure in /home/jeff/.pip/pip.log
```

we need to package `README.rst` apparently?

**Comment by radare** [comment]
Fixed. oops

**Comment by radare** [comment]
thx
